//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoices_data
    {
        public int invoice_number { get; set; }
        public int location_id { get; set; }
        public int user_id { get; set; }
    }
}
