//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int service_id { get; set; }
        public string service_name { get; set; }
        public string service_category { get; set; }
    }
}
